// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package kounatapi

import (
	"context"
	"github.com/leguminosa/kounat/internal/app/kounatapi/handler"
	character2 "github.com/leguminosa/kounat/internal/module/character"
	"github.com/leguminosa/kounat/internal/repository/character"
	"github.com/leguminosa/kounat/internal/storage/database/postgres"
	"github.com/leguminosa/kounat/internal/tools/config"
	"github.com/leguminosa/kounat/internal/tools/database"
)

// Injectors from wire.go:

func InitServer(ctx context.Context, cfg *config.Config) (Server, error) {
	pgxClient, err := database.NewPGXClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	characterDB := postgres.NewCharacterDB(pgxClient)
	characterRepository := character.NewRepository(characterDB)
	characterModule := character2.NewModule(characterRepository)
	characterHandler := handler.NewCharacter(characterModule)
	echo := provideRouter(characterHandler)
	server := NewServer(cfg, echo)
	return server, nil
}
